version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file: ./docker/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file: ./docker/pgadmin.env
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    env_file: ./docker/backend.env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile
    env_file: ./docker/frontend.env
    ports:
      - "8080:8080"
    depends_on:
      - backend

volumes:
  postgres_data:
  pgadmin_data:
