version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file: ./docker/postgres.env
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file: ./docker/pgadmin.env
    ports:
      - "5050:80"
    networks:
      - backend-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./dockers/pgadmin_servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    env_file: ./docker/backend.env
    ports:
      - "3000:3000"
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile
    env_file: ./docker/frontend.env
    ports:
      - "8080:8080"
    networks:
      - frontend-network
    depends_on:
      - backend

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data: