version: "3.9"

services:
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web-secure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your-email@example.com" # Remplacez par votre adresse email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/letsencrypt:/letsencrypt" # Pour stocker les certificats SSL
    networks:
      - frontend-network
      - backend

  postgres:
    image: postgres:latest
    env_file:
      - ./docker/postgres.env
    environment:
      TZ: "Europe/Paris"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - ./docker/pgadmin.env
    environment:
      TZ: "Europe/Paris"
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`localhost`)"
      - "traefik.http.routers.pgadmin.entrypoints=web-secure"
      - "traefik.http.routers.pgadmin.tls.certresolver=myresolver"
    networks:
      - backend
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    hostname: backend
    env_file: ./docker/backend.env
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`localhost`)"
      - "traefik.http.routers.backend.entrypoints=web-secure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"
    networks:
      - backend
      - frontend-network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile
    hostname: frontend
    env_file: ./docker/frontend.env
    ports:
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)" # Remplacez par le domaine souhaité
      - "traefik.http.routers.frontend.entrypoints=web-secure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
    networks:
      - frontend-network
    depends_on:
      - backend

networks:
  backend:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  data:
