version: "3.9"

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./docker/postgres.env
    environment:
      TZ: "Europe/Paris"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    env_file:
      - ./docker/pgadmin.env
    environment:
      TZ: "Europe/Paris"
    volumes:
      - ./docker/pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - 5050:80
    networks:
      - backend
    depends_on:
      - postgres

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    env_file: ./docker/backend.env
    ports:
      - "3000:3000"
    networks:
      - backend
      - frontend-network
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile
    env_file: ./docker/frontend.env
    ports:
      - "8080:8080"
    networks:
      - frontend-network
    depends_on:
      - backend

networks:
  backend:
  frontend-network:

volumes:
  postgres_data:
  pgadmin_data:
  data:
  